//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 01:07:27 AM EDT 
//


package bindings.askde.listings;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}PropertyType"/>
 *         &lt;element ref="{}Description"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{}Bedrooms"/>
 *           &lt;element ref="{}Bathrooms"/>
 *           &lt;element ref="{}FullBathrooms"/>
 *           &lt;element ref="{}HalfBathrooms"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}LivingArea"/>
 *         &lt;element ref="{}LotSize"/>
 *         &lt;element ref="{}YearBuilt"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "propertyType",
    "description",
    "bedrooms",
    "bathrooms",
    "fullBathrooms",
    "halfBathrooms",
    "livingArea",
    "lotSize",
    "yearBuilt"
})
@XmlRootElement(name = "BasicDetails")
public class BasicDetails {

    @XmlElement(name = "PropertyType", required = true)
    protected String propertyType;
    @XmlElement(name = "Description", required = true)
    protected String description;
    @XmlElement(name = "Bedrooms")
    protected BigDecimal bedrooms;
    @XmlElement(name = "Bathrooms")
    protected BigDecimal bathrooms;
    @XmlElement(name = "FullBathrooms")
    protected Byte fullBathrooms;
    @XmlElement(name = "HalfBathrooms")
    protected Byte halfBathrooms;
    @XmlElement(name = "LivingArea")
    protected int livingArea;
    @XmlElement(name = "LotSize", required = true)
    protected BigDecimal lotSize;
    @XmlElement(name = "YearBuilt", required = true)
    protected String yearBuilt;

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyType(String value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the bedrooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBedrooms() {
        return bedrooms;
    }

    /**
     * Sets the value of the bedrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBedrooms(BigDecimal value) {
        this.bedrooms = value;
    }

    /**
     * Gets the value of the bathrooms property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBathrooms() {
        return bathrooms;
    }

    /**
     * Sets the value of the bathrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBathrooms(BigDecimal value) {
        this.bathrooms = value;
    }

    /**
     * Gets the value of the fullBathrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getFullBathrooms() {
        return fullBathrooms;
    }

    /**
     * Sets the value of the fullBathrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setFullBathrooms(Byte value) {
        this.fullBathrooms = value;
    }

    /**
     * Gets the value of the halfBathrooms property.
     * 
     * @return
     *     possible object is
     *     {@link Byte }
     *     
     */
    public Byte getHalfBathrooms() {
        return halfBathrooms;
    }

    /**
     * Sets the value of the halfBathrooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Byte }
     *     
     */
    public void setHalfBathrooms(Byte value) {
        this.halfBathrooms = value;
    }

    /**
     * Gets the value of the livingArea property.
     * 
     */
    public int getLivingArea() {
        return livingArea;
    }

    /**
     * Sets the value of the livingArea property.
     * 
     */
    public void setLivingArea(int value) {
        this.livingArea = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLotSize(BigDecimal value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the yearBuilt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearBuilt() {
        return yearBuilt;
    }

    /**
     * Sets the value of the yearBuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearBuilt(String value) {
        this.yearBuilt = value;
    }

}
