//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 01:07:27 AM EDT 
//


package bindings.askde.listings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Status"/>
 *         &lt;element ref="{}Price"/>
 *         &lt;element ref="{}ListingUrl"/>
 *         &lt;element ref="{}MlsId"/>
 *         &lt;element ref="{}ProviderListingId"/>
 *         &lt;element ref="{}DateListed"/>
 *         &lt;element ref="{}VirtualTourUrl"/>
 *         &lt;element ref="{}ListingEmail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "price",
    "listingUrl",
    "mlsId",
    "providerListingId",
    "dateListed",
    "virtualTourUrl",
    "listingEmail"
})
@XmlRootElement(name = "ListingDetails")
public class ListingDetails {

    @XmlElement(name = "Status", required = true)
    protected String status;
    @XmlElement(name = "Price")
    protected int price;
    @XmlElement(name = "ListingUrl", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String listingUrl;
    @XmlElement(name = "MlsId", required = true)
    protected String mlsId;
    @XmlElement(name = "ProviderListingId", required = true)
    protected String providerListingId;
    @XmlElement(name = "DateListed", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateListed;
    @XmlElement(name = "VirtualTourUrl", required = true)
    protected String virtualTourUrl;
    @XmlElement(name = "ListingEmail", required = true)
    protected String listingEmail;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(int value) {
        this.price = value;
    }

    /**
     * Gets the value of the listingUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListingUrl() {
        return listingUrl;
    }

    /**
     * Sets the value of the listingUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListingUrl(String value) {
        this.listingUrl = value;
    }

    /**
     * Gets the value of the mlsId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMlsId() {
        return mlsId;
    }

    /**
     * Sets the value of the mlsId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMlsId(String value) {
        this.mlsId = value;
    }

    /**
     * Gets the value of the providerListingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderListingId() {
        return providerListingId;
    }

    /**
     * Sets the value of the providerListingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderListingId(String value) {
        this.providerListingId = value;
    }

    /**
     * Gets the value of the dateListed property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateListed() {
        return dateListed;
    }

    /**
     * Sets the value of the dateListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateListed(XMLGregorianCalendar value) {
        this.dateListed = value;
    }

    /**
     * Gets the value of the virtualTourUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVirtualTourUrl() {
        return virtualTourUrl;
    }

    /**
     * Sets the value of the virtualTourUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVirtualTourUrl(String value) {
        this.virtualTourUrl = value;
    }

    /**
     * Gets the value of the listingEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListingEmail() {
        return listingEmail;
    }

    /**
     * Sets the value of the listingEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListingEmail(String value) {
        this.listingEmail = value;
    }

}
