//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 01:07:27 AM EDT 
//


package bindings.askde.listings;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bindings.askde.listings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zip_QNAME = new QName("", "Zip");
    private final static QName _CableReady_QNAME = new QName("", "CableReady");
    private final static QName _CoolingSystem_QNAME = new QName("", "CoolingSystem");
    private final static QName _ArchitectureStyle_QNAME = new QName("", "ArchitectureStyle");
    private final static QName _PropertyType_QNAME = new QName("", "PropertyType");
    private final static QName _OnsiteLaundry_QNAME = new QName("", "OnsiteLaundry");
    private final static QName _ListingEmail_QNAME = new QName("", "ListingEmail");
    private final static QName _NumFloors_QNAME = new QName("", "NumFloors");
    private final static QName _Waterfront_QNAME = new QName("", "Waterfront");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _RoomCount_QNAME = new QName("", "RoomCount");
    private final static QName _SmallDogs_QNAME = new QName("", "SmallDogs");
    private final static QName _VirtualTourUrl_QNAME = new QName("", "VirtualTourUrl");
    private final static QName _Pool_QNAME = new QName("", "Pool");
    private final static QName _YearBuilt_QNAME = new QName("", "YearBuilt");
    private final static QName _LeaseTerm_QNAME = new QName("", "LeaseTerm");
    private final static QName _LotSize_QNAME = new QName("", "LotSize");
    private final static QName _Status_QNAME = new QName("", "Status");
    private final static QName _MlsId_QNAME = new QName("", "MlsId");
    private final static QName _Availability_QNAME = new QName("", "Availability");
    private final static QName _StartTime_QNAME = new QName("", "StartTime");
    private final static QName _BrokerageName_QNAME = new QName("", "BrokerageName");
    private final static QName _ParkingType_QNAME = new QName("", "ParkingType");
    private final static QName _City_QNAME = new QName("", "City");
    private final static QName _EmailAddress_QNAME = new QName("", "EmailAddress");
    private final static QName _ListingUrl_QNAME = new QName("", "ListingUrl");
    private final static QName _Doorman_QNAME = new QName("", "Doorman");
    private final static QName _FaxLineNumber_QNAME = new QName("", "FaxLineNumber");
    private final static QName _BrokerageEmail_QNAME = new QName("", "BrokerageEmail");
    private final static QName _Storage_QNAME = new QName("", "Storage");
    private final static QName _Price_QNAME = new QName("", "Price");
    private final static QName _Bedrooms_QNAME = new QName("", "Bedrooms");
    private final static QName _State_QNAME = new QName("", "State");
    private final static QName _MobileLineNumber_QNAME = new QName("", "MobileLineNumber");
    private final static QName _Long_QNAME = new QName("", "Long");
    private final static QName _PictureUrl_QNAME = new QName("", "PictureUrl");
    private final static QName _LastName_QNAME = new QName("", "LastName");
    private final static QName _UnitNumber_QNAME = new QName("", "UnitNumber");
    private final static QName _ViewType_QNAME = new QName("", "ViewType");
    private final static QName _Fireplace_QNAME = new QName("", "Fireplace");
    private final static QName _Cable_QNAME = new QName("", "Cable");
    private final static QName _FullBathrooms_QNAME = new QName("", "FullBathrooms");
    private final static QName _ParcelID_QNAME = new QName("", "ParcelID");
    private final static QName _Description_QNAME = new QName("", "Description");
    private final static QName _EndTime_QNAME = new QName("", "EndTime");
    private final static QName _Furnished_QNAME = new QName("", "Furnished");
    private final static QName _County_QNAME = new QName("", "County");
    private final static QName _DateListed_QNAME = new QName("", "DateListed");
    private final static QName _ProviderListingId_QNAME = new QName("", "ProviderListingId");
    private final static QName _Appliance_QNAME = new QName("", "Appliance");
    private final static QName _BrokeragePhone_QNAME = new QName("", "BrokeragePhone");
    private final static QName _Elevator_QNAME = new QName("", "Elevator");
    private final static QName _BuildingUnitCount_QNAME = new QName("", "BuildingUnitCount");
    private final static QName _CableSatTV_QNAME = new QName("", "CableSatTV");
    private final static QName _DisplayAddress_QNAME = new QName("", "DisplayAddress");
    private final static QName _NumParkingSpaces_QNAME = new QName("", "NumParkingSpaces");
    private final static QName _StreetIntersection_QNAME = new QName("", "StreetIntersection");
    private final static QName _LivingArea_QNAME = new QName("", "LivingArea");
    private final static QName _PropertyName_QNAME = new QName("", "PropertyName");
    private final static QName _Garden_QNAME = new QName("", "Garden");
    private final static QName _Cats_QNAME = new QName("", "Cats");
    private final static QName _FirstName_QNAME = new QName("", "FirstName");
    private final static QName _NewConstruction_QNAME = new QName("", "NewConstruction");
    private final static QName _NoPets_QNAME = new QName("", "NoPets");
    private final static QName _LargeDogs_QNAME = new QName("", "LargeDogs");
    private final static QName _Date_QNAME = new QName("", "Date");
    private final static QName _StreetAddress_QNAME = new QName("", "StreetAddress");
    private final static QName _Dock_QNAME = new QName("", "Dock");
    private final static QName _OfficeLineNumber_QNAME = new QName("", "OfficeLineNumber");
    private final static QName _HalfBathrooms_QNAME = new QName("", "HalfBathrooms");
    private final static QName _Bathrooms_QNAME = new QName("", "Bathrooms");
    private final static QName _Patio_QNAME = new QName("", "Patio");
    private final static QName _Lat_QNAME = new QName("", "Lat");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bindings.askde.listings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pictures }
     * 
     */
    public Pictures createPictures() {
        return new Pictures();
    }

    /**
     * Create an instance of {@link Picture }
     * 
     */
    public Picture createPicture() {
        return new Picture();
    }

    /**
     * Create an instance of {@link ExteriorTypes }
     * 
     */
    public ExteriorTypes createExteriorTypes() {
        return new ExteriorTypes();
    }

    /**
     * Create an instance of {@link ListingDetails }
     * 
     */
    public ListingDetails createListingDetails() {
        return new ListingDetails();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link PetsAllowed }
     * 
     */
    public PetsAllowed createPetsAllowed() {
        return new PetsAllowed();
    }

    /**
     * Create an instance of {@link Greenhouse }
     * 
     */
    public Greenhouse createGreenhouse() {
        return new Greenhouse();
    }

    /**
     * Create an instance of {@link Office }
     * 
     */
    public Office createOffice() {
        return new Office();
    }

    /**
     * Create an instance of {@link SecuritySystem }
     * 
     */
    public SecuritySystem createSecuritySystem() {
        return new SecuritySystem();
    }

    /**
     * Create an instance of {@link Rooms }
     * 
     */
    public Rooms createRooms() {
        return new Rooms();
    }

    /**
     * Create an instance of {@link Appliances }
     * 
     */
    public Appliances createAppliances() {
        return new Appliances();
    }

    /**
     * Create an instance of {@link Listing }
     * 
     */
    public Listing createListing() {
        return new Listing();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link RentalDetails }
     * 
     */
    public RentalDetails createRentalDetails() {
        return new RentalDetails();
    }

    /**
     * Create an instance of {@link UtilitiesIncluded }
     * 
     */
    public UtilitiesIncluded createUtilitiesIncluded() {
        return new UtilitiesIncluded();
    }

    /**
     * Create an instance of {@link BasicDetails }
     * 
     */
    public BasicDetails createBasicDetails() {
        return new BasicDetails();
    }

    /**
     * Create an instance of {@link OpenHouses }
     * 
     */
    public OpenHouses createOpenHouses() {
        return new OpenHouses();
    }

    /**
     * Create an instance of {@link OpenHouse }
     * 
     */
    public OpenHouse createOpenHouse() {
        return new OpenHouse();
    }

    /**
     * Create an instance of {@link Neighborhood }
     * 
     */
    public Neighborhood createNeighborhood() {
        return new Neighborhood();
    }

    /**
     * Create an instance of {@link RichDetails }
     * 
     */
    public RichDetails createRichDetails() {
        return new RichDetails();
    }

    /**
     * Create an instance of {@link AddtionalFeatures }
     * 
     */
    public AddtionalFeatures createAddtionalFeatures() {
        return new AddtionalFeatures();
    }

    /**
     * Create an instance of {@link HeatingFuels }
     * 
     */
    public HeatingFuels createHeatingFuels() {
        return new HeatingFuels();
    }

    /**
     * Create an instance of {@link ParkingTypes }
     * 
     */
    public ParkingTypes createParkingTypes() {
        return new ParkingTypes();
    }

    /**
     * Create an instance of {@link HighSpeedInternet }
     * 
     */
    public HighSpeedInternet createHighSpeedInternet() {
        return new HighSpeedInternet();
    }

    /**
     * Create an instance of {@link ViewTypes }
     * 
     */
    public ViewTypes createViewTypes() {
        return new ViewTypes();
    }

    /**
     * Create an instance of {@link Listings }
     * 
     */
    public Listings createListings() {
        return new Listings();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Zip")
    public JAXBElement<String> createZip(String value) {
        return new JAXBElement<String>(_Zip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CableReady")
    public JAXBElement<String> createCableReady(String value) {
        return new JAXBElement<String>(_CableReady_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CoolingSystem")
    public JAXBElement<String> createCoolingSystem(String value) {
        return new JAXBElement<String>(_CoolingSystem_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ArchitectureStyle")
    public JAXBElement<String> createArchitectureStyle(String value) {
        return new JAXBElement<String>(_ArchitectureStyle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PropertyType")
    public JAXBElement<String> createPropertyType(String value) {
        return new JAXBElement<String>(_PropertyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OnsiteLaundry")
    public JAXBElement<String> createOnsiteLaundry(String value) {
        return new JAXBElement<String>(_OnsiteLaundry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ListingEmail")
    public JAXBElement<String> createListingEmail(String value) {
        return new JAXBElement<String>(_ListingEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumFloors")
    public JAXBElement<Byte> createNumFloors(Byte value) {
        return new JAXBElement<Byte>(_NumFloors_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Waterfront")
    public JAXBElement<String> createWaterfront(String value) {
        return new JAXBElement<String>(_Waterfront_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RoomCount")
    public JAXBElement<Byte> createRoomCount(Byte value) {
        return new JAXBElement<Byte>(_RoomCount_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SmallDogs")
    public JAXBElement<String> createSmallDogs(String value) {
        return new JAXBElement<String>(_SmallDogs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VirtualTourUrl")
    public JAXBElement<String> createVirtualTourUrl(String value) {
        return new JAXBElement<String>(_VirtualTourUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Pool")
    public JAXBElement<String> createPool(String value) {
        return new JAXBElement<String>(_Pool_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YearBuilt")
    public JAXBElement<String> createYearBuilt(String value) {
        return new JAXBElement<String>(_YearBuilt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LeaseTerm")
    public JAXBElement<String> createLeaseTerm(String value) {
        return new JAXBElement<String>(_LeaseTerm_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LotSize")
    public JAXBElement<BigDecimal> createLotSize(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_LotSize_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MlsId")
    public JAXBElement<String> createMlsId(String value) {
        return new JAXBElement<String>(_MlsId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Availability")
    public JAXBElement<XMLGregorianCalendar> createAvailability(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_Availability_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StartTime")
    public JAXBElement<String> createStartTime(String value) {
        return new JAXBElement<String>(_StartTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrokerageName")
    public JAXBElement<String> createBrokerageName(String value) {
        return new JAXBElement<String>(_BrokerageName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ParkingType")
    public JAXBElement<String> createParkingType(String value) {
        return new JAXBElement<String>(_ParkingType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EmailAddress")
    public JAXBElement<String> createEmailAddress(String value) {
        return new JAXBElement<String>(_EmailAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ListingUrl")
    public JAXBElement<String> createListingUrl(String value) {
        return new JAXBElement<String>(_ListingUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Doorman")
    public JAXBElement<String> createDoorman(String value) {
        return new JAXBElement<String>(_Doorman_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FaxLineNumber")
    public JAXBElement<String> createFaxLineNumber(String value) {
        return new JAXBElement<String>(_FaxLineNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrokerageEmail")
    public JAXBElement<String> createBrokerageEmail(String value) {
        return new JAXBElement<String>(_BrokerageEmail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Storage")
    public JAXBElement<String> createStorage(String value) {
        return new JAXBElement<String>(_Storage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Price")
    public JAXBElement<Integer> createPrice(Integer value) {
        return new JAXBElement<Integer>(_Price_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bedrooms")
    public JAXBElement<BigDecimal> createBedrooms(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Bedrooms_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "State")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MobileLineNumber")
    public JAXBElement<String> createMobileLineNumber(String value) {
        return new JAXBElement<String>(_MobileLineNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Long")
    public JAXBElement<BigDecimal> createLong(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Long_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PictureUrl")
    public JAXBElement<String> createPictureUrl(String value) {
        return new JAXBElement<String>(_PictureUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LastName")
    public JAXBElement<String> createLastName(String value) {
        return new JAXBElement<String>(_LastName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnitNumber")
    public JAXBElement<String> createUnitNumber(String value) {
        return new JAXBElement<String>(_UnitNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ViewType")
    public JAXBElement<String> createViewType(String value) {
        return new JAXBElement<String>(_ViewType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Fireplace")
    public JAXBElement<String> createFireplace(String value) {
        return new JAXBElement<String>(_Fireplace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cable")
    public JAXBElement<String> createCable(String value) {
        return new JAXBElement<String>(_Cable_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FullBathrooms")
    public JAXBElement<Byte> createFullBathrooms(Byte value) {
        return new JAXBElement<Byte>(_FullBathrooms_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ParcelID")
    public JAXBElement<String> createParcelID(String value) {
        return new JAXBElement<String>(_ParcelID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EndTime")
    public JAXBElement<String> createEndTime(String value) {
        return new JAXBElement<String>(_EndTime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Furnished")
    public JAXBElement<String> createFurnished(String value) {
        return new JAXBElement<String>(_Furnished_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "County")
    public JAXBElement<String> createCounty(String value) {
        return new JAXBElement<String>(_County_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DateListed")
    public JAXBElement<XMLGregorianCalendar> createDateListed(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DateListed_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProviderListingId")
    public JAXBElement<String> createProviderListingId(String value) {
        return new JAXBElement<String>(_ProviderListingId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Appliance")
    public JAXBElement<String> createAppliance(String value) {
        return new JAXBElement<String>(_Appliance_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BrokeragePhone")
    public JAXBElement<String> createBrokeragePhone(String value) {
        return new JAXBElement<String>(_BrokeragePhone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Elevator")
    public JAXBElement<String> createElevator(String value) {
        return new JAXBElement<String>(_Elevator_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BuildingUnitCount")
    public JAXBElement<Short> createBuildingUnitCount(Short value) {
        return new JAXBElement<Short>(_BuildingUnitCount_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CableSatTV")
    public JAXBElement<String> createCableSatTV(String value) {
        return new JAXBElement<String>(_CableSatTV_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DisplayAddress")
    public JAXBElement<String> createDisplayAddress(String value) {
        return new JAXBElement<String>(_DisplayAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumParkingSpaces")
    public JAXBElement<Byte> createNumParkingSpaces(Byte value) {
        return new JAXBElement<Byte>(_NumParkingSpaces_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StreetIntersection")
    public JAXBElement<String> createStreetIntersection(String value) {
        return new JAXBElement<String>(_StreetIntersection_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LivingArea")
    public JAXBElement<Integer> createLivingArea(Integer value) {
        return new JAXBElement<Integer>(_LivingArea_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PropertyName")
    public JAXBElement<String> createPropertyName(String value) {
        return new JAXBElement<String>(_PropertyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Garden")
    public JAXBElement<String> createGarden(String value) {
        return new JAXBElement<String>(_Garden_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cats")
    public JAXBElement<String> createCats(String value) {
        return new JAXBElement<String>(_Cats_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FirstName")
    public JAXBElement<String> createFirstName(String value) {
        return new JAXBElement<String>(_FirstName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NewConstruction")
    public JAXBElement<String> createNewConstruction(String value) {
        return new JAXBElement<String>(_NewConstruction_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NoPets")
    public JAXBElement<String> createNoPets(String value) {
        return new JAXBElement<String>(_NoPets_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LargeDogs")
    public JAXBElement<String> createLargeDogs(String value) {
        return new JAXBElement<String>(_LargeDogs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StreetAddress")
    public JAXBElement<String> createStreetAddress(String value) {
        return new JAXBElement<String>(_StreetAddress_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Dock")
    public JAXBElement<String> createDock(String value) {
        return new JAXBElement<String>(_Dock_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OfficeLineNumber")
    public JAXBElement<String> createOfficeLineNumber(String value) {
        return new JAXBElement<String>(_OfficeLineNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HalfBathrooms")
    public JAXBElement<Byte> createHalfBathrooms(Byte value) {
        return new JAXBElement<Byte>(_HalfBathrooms_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Bathrooms")
    public JAXBElement<BigDecimal> createBathrooms(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Bathrooms_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Patio")
    public JAXBElement<String> createPatio(String value) {
        return new JAXBElement<String>(_Patio_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Lat")
    public JAXBElement<BigDecimal> createLat(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Lat_QNAME, BigDecimal.class, null, value);
    }

}
