//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 01:07:27 AM EDT 
//


package bindings.askde.listings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}BrokerageName"/>
 *         &lt;element ref="{}BrokeragePhone"/>
 *         &lt;element ref="{}BrokerageEmail"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "brokerageName",
    "brokeragePhone",
    "brokerageEmail"
})
@XmlRootElement(name = "Office")
public class Office {

    @XmlElement(name = "BrokerageName", required = true)
    protected String brokerageName;
    @XmlElement(name = "BrokeragePhone", required = true)
    protected String brokeragePhone;
    @XmlElement(name = "BrokerageEmail", required = true)
    protected String brokerageEmail;

    /**
     * Gets the value of the brokerageName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerageName() {
        return brokerageName;
    }

    /**
     * Sets the value of the brokerageName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerageName(String value) {
        this.brokerageName = value;
    }

    /**
     * Gets the value of the brokeragePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokeragePhone() {
        return brokeragePhone;
    }

    /**
     * Sets the value of the brokeragePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokeragePhone(String value) {
        this.brokeragePhone = value;
    }

    /**
     * Gets the value of the brokerageEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokerageEmail() {
        return brokerageEmail;
    }

    /**
     * Sets the value of the brokerageEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokerageEmail(String value) {
        this.brokerageEmail = value;
    }

}
