//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 01:07:27 AM EDT 
//


package bindings.askde.listings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}SmallDogs"/>
 *         &lt;element ref="{}LargeDogs"/>
 *         &lt;element ref="{}NoPets"/>
 *         &lt;element ref="{}Cats"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "smallDogs",
    "largeDogs",
    "noPets",
    "cats"
})
@XmlRootElement(name = "PetsAllowed")
public class PetsAllowed {

    @XmlElement(name = "SmallDogs")
    protected String smallDogs;
    @XmlElement(name = "LargeDogs")
    protected String largeDogs;
    @XmlElement(name = "NoPets")
    protected String noPets;
    @XmlElement(name = "Cats")
    protected String cats;

    /**
     * Gets the value of the smallDogs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmallDogs() {
        return smallDogs;
    }

    /**
     * Sets the value of the smallDogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmallDogs(String value) {
        this.smallDogs = value;
    }

    /**
     * Gets the value of the largeDogs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLargeDogs() {
        return largeDogs;
    }

    /**
     * Sets the value of the largeDogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLargeDogs(String value) {
        this.largeDogs = value;
    }

    /**
     * Gets the value of the noPets property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoPets() {
        return noPets;
    }

    /**
     * Sets the value of the noPets property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoPets(String value) {
        this.noPets = value;
    }

    /**
     * Gets the value of the cats property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCats() {
        return cats;
    }

    /**
     * Sets the value of the cats property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCats(String value) {
        this.cats = value;
    }

}
