//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 01:07:27 AM EDT 
//


package bindings.askde.listings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Availability"/>
 *         &lt;element ref="{}LeaseTerm"/>
 *         &lt;element ref="{}UtilitiesIncluded"/>
 *         &lt;element ref="{}PetsAllowed"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "availability",
    "leaseTerm",
    "utilitiesIncluded",
    "petsAllowed"
})
@XmlRootElement(name = "RentalDetails")
public class RentalDetails {

    @XmlElement(name = "Availability", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar availability;
    @XmlElement(name = "LeaseTerm", required = true)
    protected String leaseTerm;
    @XmlElement(name = "UtilitiesIncluded", required = true)
    protected UtilitiesIncluded utilitiesIncluded;
    @XmlElement(name = "PetsAllowed", required = true)
    protected PetsAllowed petsAllowed;

    /**
     * Gets the value of the availability property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAvailability() {
        return availability;
    }

    /**
     * Sets the value of the availability property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailability(XMLGregorianCalendar value) {
        this.availability = value;
    }

    /**
     * Gets the value of the leaseTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaseTerm() {
        return leaseTerm;
    }

    /**
     * Sets the value of the leaseTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaseTerm(String value) {
        this.leaseTerm = value;
    }

    /**
     * Gets the value of the utilitiesIncluded property.
     * 
     * @return
     *     possible object is
     *     {@link UtilitiesIncluded }
     *     
     */
    public UtilitiesIncluded getUtilitiesIncluded() {
        return utilitiesIncluded;
    }

    /**
     * Sets the value of the utilitiesIncluded property.
     * 
     * @param value
     *     allowed object is
     *     {@link UtilitiesIncluded }
     *     
     */
    public void setUtilitiesIncluded(UtilitiesIncluded value) {
        this.utilitiesIncluded = value;
    }

    /**
     * Gets the value of the petsAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link PetsAllowed }
     *     
     */
    public PetsAllowed getPetsAllowed() {
        return petsAllowed;
    }

    /**
     * Sets the value of the petsAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link PetsAllowed }
     *     
     */
    public void setPetsAllowed(PetsAllowed value) {
        this.petsAllowed = value;
    }

}
