//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 01:07:27 AM EDT 
//


package bindings.askde.listings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}AddtionalFeatures"/>
 *         &lt;element ref="{}Appliances"/>
 *         &lt;element ref="{}ArchitectureStyle"/>
 *         &lt;element ref="{}BuildingUnitCount"/>
 *         &lt;element ref="{}CableReady"/>
 *         &lt;element ref="{}CoolingSystem"/>
 *         &lt;element ref="{}Dock"/>
 *         &lt;element ref="{}Doorman"/>
 *         &lt;element ref="{}Elevator"/>
 *         &lt;element ref="{}ExteriorTypes"/>
 *         &lt;element ref="{}Fireplace"/>
 *         &lt;element ref="{}Garden"/>
 *         &lt;element ref="{}Greenhouse"/>
 *         &lt;element ref="{}HeatingFuels"/>
 *         &lt;element ref="{}NewConstruction" minOccurs="0"/>
 *         &lt;element ref="{}NumFloors"/>
 *         &lt;element ref="{}NumParkingSpaces"/>
 *         &lt;element ref="{}ParkingTypes"/>
 *         &lt;element ref="{}Patio"/>
 *         &lt;element ref="{}Pool"/>
 *         &lt;element ref="{}RoomCount"/>
 *         &lt;element ref="{}Rooms"/>
 *         &lt;element ref="{}SecuritySystem"/>
 *         &lt;element ref="{}Storage"/>
 *         &lt;element ref="{}PropertyName"/>
 *         &lt;element ref="{}Furnished"/>
 *         &lt;element ref="{}HighSpeedInternet"/>
 *         &lt;element ref="{}OnsiteLaundry"/>
 *         &lt;element ref="{}CableSatTV"/>
 *         &lt;element ref="{}ViewTypes"/>
 *         &lt;element ref="{}Waterfront"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addtionalFeatures",
    "appliances",
    "architectureStyle",
    "buildingUnitCount",
    "cableReady",
    "coolingSystem",
    "dock",
    "doorman",
    "elevator",
    "exteriorTypes",
    "fireplace",
    "garden",
    "greenhouse",
    "heatingFuels",
    "newConstruction",
    "numFloors",
    "numParkingSpaces",
    "parkingTypes",
    "patio",
    "pool",
    "roomCount",
    "rooms",
    "securitySystem",
    "storage",
    "propertyName",
    "furnished",
    "highSpeedInternet",
    "onsiteLaundry",
    "cableSatTV",
    "viewTypes",
    "waterfront"
})
@XmlRootElement(name = "RichDetails")
public class RichDetails {

    @XmlElement(name = "AddtionalFeatures", required = true)
    protected AddtionalFeatures addtionalFeatures;
    @XmlElement(name = "Appliances", required = true)
    protected Appliances appliances;
    @XmlElement(name = "ArchitectureStyle", required = true)
    protected String architectureStyle;
    @XmlElement(name = "BuildingUnitCount")
    protected short buildingUnitCount;
    @XmlElement(name = "CableReady", required = true)
    protected String cableReady;
    @XmlElement(name = "CoolingSystem", required = true)
    protected String coolingSystem;
    @XmlElement(name = "Dock", required = true)
    protected String dock;
    @XmlElement(name = "Doorman", required = true)
    protected String doorman;
    @XmlElement(name = "Elevator", required = true)
    protected String elevator;
    @XmlElement(name = "ExteriorTypes", required = true)
    protected ExteriorTypes exteriorTypes;
    @XmlElement(name = "Fireplace", required = true)
    protected String fireplace;
    @XmlElement(name = "Garden", required = true)
    protected String garden;
    @XmlElement(name = "Greenhouse", required = true)
    protected Greenhouse greenhouse;
    @XmlElement(name = "HeatingFuels", required = true)
    protected HeatingFuels heatingFuels;
    @XmlElement(name = "NewConstruction")
    protected String newConstruction;
    @XmlElement(name = "NumFloors")
    protected byte numFloors;
    @XmlElement(name = "NumParkingSpaces")
    protected byte numParkingSpaces;
    @XmlElement(name = "ParkingTypes", required = true)
    protected ParkingTypes parkingTypes;
    @XmlElement(name = "Patio", required = true)
    protected String patio;
    @XmlElement(name = "Pool", required = true)
    protected String pool;
    @XmlElement(name = "RoomCount")
    protected byte roomCount;
    @XmlElement(name = "Rooms", required = true)
    protected Rooms rooms;
    @XmlElement(name = "SecuritySystem", required = true)
    protected SecuritySystem securitySystem;
    @XmlElement(name = "Storage", required = true)
    protected String storage;
    @XmlElement(name = "PropertyName", required = true)
    protected String propertyName;
    @XmlElement(name = "Furnished", required = true)
    protected String furnished;
    @XmlElement(name = "HighSpeedInternet", required = true)
    protected HighSpeedInternet highSpeedInternet;
    @XmlElement(name = "OnsiteLaundry", required = true)
    protected String onsiteLaundry;
    @XmlElement(name = "CableSatTV", required = true)
    protected String cableSatTV;
    @XmlElement(name = "ViewTypes", required = true)
    protected ViewTypes viewTypes;
    @XmlElement(name = "Waterfront", required = true)
    protected String waterfront;

    /**
     * Gets the value of the addtionalFeatures property.
     * 
     * @return
     *     possible object is
     *     {@link AddtionalFeatures }
     *     
     */
    public AddtionalFeatures getAddtionalFeatures() {
        return addtionalFeatures;
    }

    /**
     * Sets the value of the addtionalFeatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddtionalFeatures }
     *     
     */
    public void setAddtionalFeatures(AddtionalFeatures value) {
        this.addtionalFeatures = value;
    }

    /**
     * Gets the value of the appliances property.
     * 
     * @return
     *     possible object is
     *     {@link Appliances }
     *     
     */
    public Appliances getAppliances() {
        return appliances;
    }

    /**
     * Sets the value of the appliances property.
     * 
     * @param value
     *     allowed object is
     *     {@link Appliances }
     *     
     */
    public void setAppliances(Appliances value) {
        this.appliances = value;
    }

    /**
     * Gets the value of the architectureStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchitectureStyle() {
        return architectureStyle;
    }

    /**
     * Sets the value of the architectureStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchitectureStyle(String value) {
        this.architectureStyle = value;
    }

    /**
     * Gets the value of the buildingUnitCount property.
     * 
     */
    public short getBuildingUnitCount() {
        return buildingUnitCount;
    }

    /**
     * Sets the value of the buildingUnitCount property.
     * 
     */
    public void setBuildingUnitCount(short value) {
        this.buildingUnitCount = value;
    }

    /**
     * Gets the value of the cableReady property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCableReady() {
        return cableReady;
    }

    /**
     * Sets the value of the cableReady property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCableReady(String value) {
        this.cableReady = value;
    }

    /**
     * Gets the value of the coolingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoolingSystem() {
        return coolingSystem;
    }

    /**
     * Sets the value of the coolingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoolingSystem(String value) {
        this.coolingSystem = value;
    }

    /**
     * Gets the value of the dock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDock() {
        return dock;
    }

    /**
     * Sets the value of the dock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDock(String value) {
        this.dock = value;
    }

    /**
     * Gets the value of the doorman property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDoorman() {
        return doorman;
    }

    /**
     * Sets the value of the doorman property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDoorman(String value) {
        this.doorman = value;
    }

    /**
     * Gets the value of the elevator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElevator() {
        return elevator;
    }

    /**
     * Sets the value of the elevator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElevator(String value) {
        this.elevator = value;
    }

    /**
     * Gets the value of the exteriorTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ExteriorTypes }
     *     
     */
    public ExteriorTypes getExteriorTypes() {
        return exteriorTypes;
    }

    /**
     * Sets the value of the exteriorTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExteriorTypes }
     *     
     */
    public void setExteriorTypes(ExteriorTypes value) {
        this.exteriorTypes = value;
    }

    /**
     * Gets the value of the fireplace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFireplace() {
        return fireplace;
    }

    /**
     * Sets the value of the fireplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFireplace(String value) {
        this.fireplace = value;
    }

    /**
     * Gets the value of the garden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGarden() {
        return garden;
    }

    /**
     * Sets the value of the garden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGarden(String value) {
        this.garden = value;
    }

    /**
     * Gets the value of the greenhouse property.
     * 
     * @return
     *     possible object is
     *     {@link Greenhouse }
     *     
     */
    public Greenhouse getGreenhouse() {
        return greenhouse;
    }

    /**
     * Sets the value of the greenhouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Greenhouse }
     *     
     */
    public void setGreenhouse(Greenhouse value) {
        this.greenhouse = value;
    }

    /**
     * Gets the value of the heatingFuels property.
     * 
     * @return
     *     possible object is
     *     {@link HeatingFuels }
     *     
     */
    public HeatingFuels getHeatingFuels() {
        return heatingFuels;
    }

    /**
     * Sets the value of the heatingFuels property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeatingFuels }
     *     
     */
    public void setHeatingFuels(HeatingFuels value) {
        this.heatingFuels = value;
    }

    /**
     * Gets the value of the newConstruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewConstruction() {
        return newConstruction;
    }

    /**
     * Sets the value of the newConstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewConstruction(String value) {
        this.newConstruction = value;
    }

    /**
     * Gets the value of the numFloors property.
     * 
     */
    public byte getNumFloors() {
        return numFloors;
    }

    /**
     * Sets the value of the numFloors property.
     * 
     */
    public void setNumFloors(byte value) {
        this.numFloors = value;
    }

    /**
     * Gets the value of the numParkingSpaces property.
     * 
     */
    public byte getNumParkingSpaces() {
        return numParkingSpaces;
    }

    /**
     * Sets the value of the numParkingSpaces property.
     * 
     */
    public void setNumParkingSpaces(byte value) {
        this.numParkingSpaces = value;
    }

    /**
     * Gets the value of the parkingTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ParkingTypes }
     *     
     */
    public ParkingTypes getParkingTypes() {
        return parkingTypes;
    }

    /**
     * Sets the value of the parkingTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParkingTypes }
     *     
     */
    public void setParkingTypes(ParkingTypes value) {
        this.parkingTypes = value;
    }

    /**
     * Gets the value of the patio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatio() {
        return patio;
    }

    /**
     * Sets the value of the patio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatio(String value) {
        this.patio = value;
    }

    /**
     * Gets the value of the pool property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPool() {
        return pool;
    }

    /**
     * Sets the value of the pool property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPool(String value) {
        this.pool = value;
    }

    /**
     * Gets the value of the roomCount property.
     * 
     */
    public byte getRoomCount() {
        return roomCount;
    }

    /**
     * Sets the value of the roomCount property.
     * 
     */
    public void setRoomCount(byte value) {
        this.roomCount = value;
    }

    /**
     * Gets the value of the rooms property.
     * 
     * @return
     *     possible object is
     *     {@link Rooms }
     *     
     */
    public Rooms getRooms() {
        return rooms;
    }

    /**
     * Sets the value of the rooms property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rooms }
     *     
     */
    public void setRooms(Rooms value) {
        this.rooms = value;
    }

    /**
     * Gets the value of the securitySystem property.
     * 
     * @return
     *     possible object is
     *     {@link SecuritySystem }
     *     
     */
    public SecuritySystem getSecuritySystem() {
        return securitySystem;
    }

    /**
     * Sets the value of the securitySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecuritySystem }
     *     
     */
    public void setSecuritySystem(SecuritySystem value) {
        this.securitySystem = value;
    }

    /**
     * Gets the value of the storage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorage() {
        return storage;
    }

    /**
     * Sets the value of the storage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorage(String value) {
        this.storage = value;
    }

    /**
     * Gets the value of the propertyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * Sets the value of the propertyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyName(String value) {
        this.propertyName = value;
    }

    /**
     * Gets the value of the furnished property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFurnished() {
        return furnished;
    }

    /**
     * Sets the value of the furnished property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFurnished(String value) {
        this.furnished = value;
    }

    /**
     * Gets the value of the highSpeedInternet property.
     * 
     * @return
     *     possible object is
     *     {@link HighSpeedInternet }
     *     
     */
    public HighSpeedInternet getHighSpeedInternet() {
        return highSpeedInternet;
    }

    /**
     * Sets the value of the highSpeedInternet property.
     * 
     * @param value
     *     allowed object is
     *     {@link HighSpeedInternet }
     *     
     */
    public void setHighSpeedInternet(HighSpeedInternet value) {
        this.highSpeedInternet = value;
    }

    /**
     * Gets the value of the onsiteLaundry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnsiteLaundry() {
        return onsiteLaundry;
    }

    /**
     * Sets the value of the onsiteLaundry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnsiteLaundry(String value) {
        this.onsiteLaundry = value;
    }

    /**
     * Gets the value of the cableSatTV property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCableSatTV() {
        return cableSatTV;
    }

    /**
     * Sets the value of the cableSatTV property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCableSatTV(String value) {
        this.cableSatTV = value;
    }

    /**
     * Gets the value of the viewTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ViewTypes }
     *     
     */
    public ViewTypes getViewTypes() {
        return viewTypes;
    }

    /**
     * Sets the value of the viewTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViewTypes }
     *     
     */
    public void setViewTypes(ViewTypes value) {
        this.viewTypes = value;
    }

    /**
     * Gets the value of the waterfront property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaterfront() {
        return waterfront;
    }

    /**
     * Sets the value of the waterfront property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaterfront(String value) {
        this.waterfront = value;
    }

}
